try {
    console.log('Ola')
}
catch (erro) {
    console.log('Erro do tipo: '+erro)
}
finally {
    console.log('Saindo...')
}